In [102]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import approx_fprime
from scipy.optimize import minimize
from math import cos, sin

### Задание 1: 
Посчитайте частные производные функций в точках
(как обычно, необходимо решение на бумажке или в LaTeX и на numpy):

1) $f(x,y)=2x^2y^3 + 1/x + y^2x + 7$ в точке $(1,2)$

2) $f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y$

1) 

 $ f'_x (x,y) = 4xy^3 - 1/x^2 + y^2 $
 
 $ f'_x (1,2) = 4*1*2^3 - 1/1^2 + 2^2 = 32 - 1 + 4 = 35 $
 
 $ f'_x (1,2) = 35 $
 
 $ f'_y (x,y) = 6x^2y^2 + 2yx $
 
 $ f'_y (1,2) = 6*1^2*2^2 + 2*2*1 = 24 + 4 = 28 $
 
 $ f'_y (1,2) = 28 $

2)

$ f'_x (x,y) = 2xy - y*cos(xy) - 2x*sin(x^2) $

$ f'_x (1,2) = 2*1*2 - 2*cos(1*2) - 2*1*sin(1^2) $

$ f'_x (1,2) = 4 - 0.832 - 1.683 = 1.485 $

$ f'_y (x,y) = x^2 - x*cos(xy) + 6 $

$ f'_y (1,2) = 1^2 - 1*cos(1*2) + 6 $

$ f'_y (1,2) = 2 - 0.416 + 6 = 7.584 $

In [103]:
def f1 (x):
    return (2 * pow(x[0], 2) * pow(x[1], 3)) + (1/x[0]) + (pow(x[1], 2) * x[0]) + 7

In [104]:
eps = np.finfo(np.float32).eps
eps

1.1920929e-07

In [105]:
x = [1, 2]

In [106]:
approx_fprime(x, f1, [eps, eps])

array([35.00000203, 28.00000155])

In [107]:
eps1 = np.finfo(float).eps
eps1

2.220446049250313e-16

In [108]:
approx_fprime(x, f1, [eps1, eps1])

array([32.,  0.])

In [109]:
def f2(x):
    return pow(x[0], 2) * x[1] - sin(x[0] * x[1]) + cos(pow(x[0], 2)) + 6 * x[1]

In [110]:
approx_fprime(x, f2, [eps, eps])

array([3.14935194, 7.4161469 ])

In [111]:
approx_fprime(x, f2, [eps1, eps1])

array([8., 0.])

Видим, насколько результат вычисления градиента отличается при разных условиях, передаваемых встроенной функции. При существенном уменьшении шага приближения, результат получается совсем неверный. Для комбинации периодических функций результат не вполне верный.

### Задание 2:

Градиентный спуск своими руками

In [112]:
def f(x):
    return (x[0]**2) + (x[1]**2) 

In [113]:
x = np.array([100, 200])
lr = 0.1

Поскольку функция имеет простой вид, частные производные включим в цикл сразу в виде арифметических выражений

In [114]:
for i in range(100):
    # Calculate gradient
    grad = np.array([2*x[0], 2*x[1]]) # Your code here (функция для вычисления градиента есть в лекционном ноутбуке)
    
    # Update x with gradient
    x = x - lr * grad # Your code here (смотри слайд презентации про градиентный спуск)
x

array([2.03703598e-08, 4.07407195e-08])

In [115]:
print("Минимум достигается в: ", x)
print("Значение функции в минимуме: ", f(x))

Минимум достигается в:  [2.03703598e-08 4.07407195e-08]
Значение функции в минимуме:  2.0747577844404994e-15


Из общих свойств полиномов мы знаем, что функция будет иметь глобальный минимум в точке (0,0). Градиентный спуск остановился на значаниях аргументов порядка $10^{-18}$ что сопоставимо с 0 в условиях допустимой погрешности.

Проверка с помощью встроенной функции numpy: 

In [116]:
x = np.array([100, 200]) # Необходимо переопределить х на начальные уровни

In [117]:
res = minimize(f, x, method='nelder-mead', options={'xtol': 1e-8, 'disp': True})

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 85
         Function evaluations: 164
